server:
  port: 9527

spring:
  application:
    name: mt-zuul
  profiles:
    include: auth
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    instance-id: mt-zuul
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

zuul:
  # swagger文档会重复扫描服务路径和路由映射的路径 需要统一一个入口
  ignored-services: '*'
  routes:
    #    下面等同于  serviceId: mt-server-user path: /user2/**
    mt-server-user: /customerServer/**
    mt-server-comment: /commentServer/**
    mt-server-film: /filmServer/**
    mt-server-cinema: /cinemaServer/**
    mt-server-schedule: /scheduleServer/**
    mt-server-order: /orderServer/**
    mt-server-pay: /payServer/**
    mt-server-upload: /uploadServer/**
    mt-server-messages: /messageServer/**





