server:
  port: 8005

spring:
  application:
    name: mt-server-comment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mt_database?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    name: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  instance:
    instance-id: mt-server-comment
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/



